### PR TITLE
Separate identity from user

### PR DESCRIPTION
**Pull request by jamesthomasonjr**

### CODE REVIEW

**Comment by skluck** [comment]
Why is this necessary?

**Comment by jamesthomasonjr** [comment]
If we're going to support more identity providers than just internal users (like LDAP and github) and we want to eventually separate them to allow for connecting multiple identities to a single user (as suggested in hal-platform/hal#57), my thought is that it would be easiest to get the separation out of the way before all the individual identity provider work.

**Comment by skluck** [comment]
No, I mentioned elsewhere a user has an IDP. Using another IDP is another user account.

We already support both LDAP and internal using this. Dealing with tying multiple identities to a single user is a harder problem than it seems, and its not something we need to support any time soon. It's just not worth it right now.

**Comment by skluck** [comment]
Also - any changes to current schema should be in the same migrations we have. That's until we hit 3.0 and are stable, then we will start adding new migrations. But for now we can change the original ones so we don't have to deal with state.

It should be a regular occurence where you tear down and build up the db if they change.

**Comment by skluck** [comment]
Please no more commits, I have working changes which are rebased. I will merge.

**Pull request merged**
